"""Updates Email from User

Revision ID: 864792a7488f
Revises: b72b37eefb20
Create Date: 2024-10-17 23:38:06.029983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864792a7488f'
down_revision = 'b72b37eefb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
