"""SECOND

Revision ID: e3a6f44dd703
Revises: a1dedcb9b590
Create Date: 2024-10-16 23:31:41.224967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a6f44dd703'
down_revision = 'a1dedcb9b590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))
        batch_op.drop_column('steps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
